# Site settings
title: BioJS Tutorial
email: 
description: "Presented by BioJS"
baseurl: ""
url: "http://vizbi.biojs.net/"
github: "biojs-edu/vizbi"
twitter_username: 
github_username:  

analytics :
  provider : google
  google :
      tracking_id : 'UA-51509688-3'

plugins: ./_plugins

# Build settings
markdown: kramdown
kramdown:
   input: GFM

permalink: pretty
